### ISSUE TITLE
Where's the source code?

### ISSUE THREAD

**Issue by resynth1943** [snowpackjs/skypack-cdn#90]

**Comment by drwpow** [comment]
This is just the issue tracker for skypack.dev; the source code is not open. But it uses [esinstall](https://github.com/snowpackjs/snowpack/tree/main/esinstall) under the hood for preparing ESM packages, and that part is open source.

**Comment by resynth1943** [comment]
Thank you for your swift reply.

Might I inquire as to why it is not open-source?

**Comment by drwpow** [comment]
Sure! Basically, a few reasons:

1. The Skypack CDN is the product of a company. You can always count on the current Skypack CDN being free, and reliable, and able to be used for personal and commercial use. We don’t collect/sell any of your data either (it’s nice that browsers, when requesting JS, don’t really send that much info anyway so it’s secure because of how the web is built). But in the future Skypack CDN will offer paid features for companies that need them (we’ll keep the current CDN free and the same; don’t worry) and we don’t want to make these new paid features public.
2. It’s complicated. Even if we did make the source code public, it’s distributed across many edge networks and requires many moving pieces, such that the source code couldn’t even live in one repo.
3. We don’t need contributors / don’t want maintenance. Again, with this being a company product, we neither need contributors here, nor do we want to answer support requests for people hosting their own CDN. If you want to build your own ESM CDN then all the power to you! But we don’t have time to answer questions about it.

**Comment by resynth1943** [comment]
If you don't mind my asking, which position in the company do you represent?

> The Skypack CDN is the product of a company. You can always count on the current Skypack CDN being free, and reliable, and able to be used for personal and commercial use. We don’t collect/sell any of your data either (it’s nice that browsers, when requesting JS, don’t really send that much info anyway so it’s secure because of how the web is built). But in the future Skypack CDN will offer paid features for companies that need them (we’ll keep the current CDN free and the same; don’t worry) and we don’t want to make these new paid features public.

The same model of thinking was adopted with NPM, and look where it got the JavaScript ecosystem. Nevertheless, I can understand your reasoning, and can appreciate that, unlike NPM, this isn't practically forced upon developers. :thumbsup:

Aside from some... annoying issues (like Node's `crypto` throwing "not found" errors) in Deno. Hopefully you guys can fix the problems with Deno, and perhaps this'd be a solid alternative to NPM (aside from the obvious [*centralisation downsides*](https://resynth1943.net/articles/imbalance-of-power-in-javascript/)).

> We don’t need contributors / don’t want maintenance.

[So people shouldn't send that email after all?](https://www.skypack.dev/about) :stuck_out_tongue:

> we neither need contributors here, nor do we want to answer support requests for people hosting their own CDN. 

Yeah, that's a fair point. I've seen some companies get 'round this by explicitly declaring that they do not offer official support, leaving that job to the community, e.g. Stack Overflow users.

Honestly, in this case, *I think open-sourcing it would be a mixed blessing.* On one hand, people are free to host it, but on the other, (judging from what you've said) it'd most likely face the same demise as [reddit](https://github.com/reddit/reddit). Fractured responses, lack of support and no clear build instructions don't instill courage; nevertheless, I wish you the best of luck in developing Skypack.

**Just one more question**, if you're allowed to respond: with your plans for 'paid features', would this be similar to NPM's paid private registry? Curious to see how that would work: initially, I'd imagine you'd support importing private packages from NPM, which doesn't sound like a bad idea.

**Comment by drwpow** [comment]
> Just one more question, if you're allowed to respond: with your plans for 'paid features', would this be similar to NPM's paid private registry? Curious to see how that would work: initially, I'd imagine you'd support importing private packages from NPM, which doesn't sound like a bad idea.

Yes! Support for private packages is definitely on the roadmap. We'll have more updates on this early next year.
